import { useEffect, useState } from "react";
import { api } from "../../lib/api";
import { useToast } from "../../lib/toast";

type Variant = { id:number; generation:number; mutation_type:string; label:string; expression:string; settings:any; reason:string; status:string; alpha_id:string; fitness:number|null; sharpe:number|null; turnover:number|null; parent_variant_id:number; execution_key?:string; };
type Family = { id:number; name:string; status:string; region:string; parent_alpha_id:string; generation:number; variant_budget:number; variants_created:number; variants_passed:number; variants_failed:number; variants:Variant[]; hypothesis:any; notes:string; };

export function AlphaEvolution(){
  const {toast,toastErr}=useToast();
  const [families,setFamilies]=useState<Family[]>([]); const [alpha,setAlpha]=useState(""); const [selected,setSelected]=useState<Family|null>(null); const [busy,setBusy]=useState(false); const [diag,setDiag]=useState<any>(null);
  async function load(){ const d=await api.get<{families:Family[]}>("/evolution/families"); if(d.error)return toastErr(d.error); const fs=d.families||[]; setFamilies(fs); if(selected){const f=fs.find(x=>x.id===selected.id); if(f)setSelected(f);} }
  useEffect(()=>{load()},[]);
  async function diagnose(){ if(!alpha.trim())return; const d=await api.get<any>(`/evolution/diagnose/${encodeURIComponent(alpha.trim())}`); if(d.error)return toastErr(d.error); setDiag(d); }
  async function start(){ if(!alpha.trim())return toast("Enter the failed BRAIN alpha ID first.","warn"); setBusy(true); const d=await api.post<any>("/evolution/families",{alpha_id:alpha.trim(),budget:30}); setBusy(false); if(d.error)return toastErr(d.error); setSelected(d); await load(); toast("Alpha family created. The failed parent is preserved.","ok"); }
  async function evolve(){ if(!selected)return; const before=selected.variants_created; setBusy(true); const d=await api.post<any>("/evolution/evolve",{family_id:selected.id,max_variants:10}); setBusy(false); if(d.error)return toastErr(d.error); setSelected(d); await load(); toast(`${Math.max(0,(d.variants_created||0)-before)} controlled variant(s) proposed.`,"ok"); }
  async function simulateVariant(id:number){ setBusy(true); const d=await api.post<any>("/evolution/simulate-variant",{variant_id:id}); setBusy(false); if(d.error)return toastErr(d.error); toast(`Simulation queued (job ${d.job_id}).`,"ok"); await load(); }
  async function close(){ if(!selected)return; const reason=window.prompt("Why close this research branch?", "No promising variants remain.")||""; const d=await api.post<any>("/evolution/close",{family_id:selected.id,reason}); if(d.error)return toastErr(d.error); setSelected(d); await load(); }
  async function abandon(id:number){ const reason=window.prompt("Why abandon this variant?", "Not worth further testing.")||""; const d=await api.post<any>("/evolution/abandon",{variant_id:id,reason}); if(d.error)return toastErr(d.error); await load(); }
  return <div style={{display:"flex",flexDirection:"column",gap:12,flex:1,minHeight:0}}>
    <div className="panel" style={{padding:14}}><div className="dx-head"><b>Alpha Evolution Engine</b><span className="mut">failure → diagnosis → controlled mutation → simulation → comparison</span></div>
      <div className="mut" style={{fontSize:12,margin:"6px 0 10px"}}>Failed alphas are preserved as research lineage. ACE changes one dimension at a time where possible. It never auto-submits.</div>
      <div style={{display:"flex",gap:8,alignItems:"center"}}><input placeholder="Failed BRAIN alpha ID, e.g. 123456" value={alpha} onChange={e=>setAlpha(e.target.value)} style={{flex:1}}/><button className="btn ghost sm" onClick={diagnose} disabled={busy}>Diagnose</button><button className="btn sm" onClick={start} disabled={busy}>Start evolution</button></div>
      {diag&&<div style={{marginTop:12,padding:10,background:"var(--surface-2)",borderRadius:8}}><b>{diag.diagnosis}</b><div className="mut" style={{fontSize:11,marginTop:4}}>{(diag.failure_codes||[]).join(" · ")||"No failure code"}</div><div style={{fontSize:11,marginTop:5}}>{(diag.reasons||[]).join("; ")||"Passed"}</div></div>}
    </div>
    <div style={{display:"grid",gridTemplateColumns:"minmax(280px,340px) 1fr",gap:12,flex:1,minHeight:0}}>
      <div className="panel" style={{padding:12,overflow:"auto"}}><div className="dx-head"><b>Families</b><button className="btn ghost sm" style={{marginLeft:"auto"}} onClick={load}>↻</button></div>{!families.length?<div className="empty">No evolution families yet.</div>:families.map(f=><div key={f.id} onClick={()=>setSelected(f)} style={{padding:10,marginTop:7,border:"1px solid var(--border)",borderRadius:8,cursor:"pointer",background:selected?.id===f.id?"var(--surface-2)":"transparent"}}><b>#{f.id} {f.name}</b><div className="mut" style={{fontSize:11}}>{f.parent_alpha_id} · gen {f.generation} · {f.variants_created} variants</div><div style={{fontSize:11,marginTop:3}}>{f.variants_passed} passed · {f.variants_failed} failed · {f.status}</div></div>)}</div>
      <div className="panel" style={{padding:14,overflow:"auto"}}>{!selected?<div className="empty">Select an alpha family to inspect its lineage.</div>:<><div className="dx-head"><b>Family #{selected.id}</b><span className="mut">{selected.name}</span><span style={{marginLeft:"auto",display:"flex",gap:6}}>{selected.status==="open"&&<button className="btn sm" onClick={evolve} disabled={busy}>＋ Propose next variants</button>}<button className="btn ghost sm" onClick={close} disabled={busy||selected.status!=="open"}>Close branch</button></span></div>
        <div style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:8,margin:"10px 0"}}>{[["Status",selected.status],["Parent",selected.parent_alpha_id],["Generation",selected.generation],["Budget",selected.variant_budget],["Variants",selected.variants_created]].map(([k,v])=><div key={String(k)} style={{padding:9,background:"var(--surface-2)",borderRadius:7}}><div className="mut" style={{fontSize:10}}>{k}</div><b>{v}</b></div>)}</div>
        <table><thead><tr><th>Gen</th><th>Type</th><th>Expression / settings</th><th>Why</th><th>Result</th><th>Actions</th></tr></thead><tbody>{selected.variants.map(v=><tr key={v.id}><td>{v.generation}</td><td><span className="badge">{v.mutation_type}</span><div className="mut" style={{fontSize:10}}>{v.label}</div></td><td><code>{v.expression}</code>{Object.keys(v.settings||{}).length>0&&<div className="mut" style={{fontSize:10}}>{JSON.stringify(v.settings)}</div>}</td><td style={{maxWidth:300,fontSize:11}}>{v.reason}</td><td>{v.status}{v.fitness!=null&&<div className="mut" style={{fontSize:10}}>Fit {Math.abs(v.fitness).toFixed(3)} · Sh {v.sharpe==null?"—":Math.abs(v.sharpe).toFixed(3)}</div>}</td><td style={{whiteSpace:"nowrap"}}>{["proposed","failed"].includes(v.status)&&<button className="btn sm" onClick={()=>simulateVariant(v.id)} disabled={busy}>Simulate</button>}{["proposed","failed"].includes(v.status)&&<button className="btn ghost sm" onClick={()=>abandon(v.id)} style={{marginLeft:5}}>Abandon</button>}</td></tr>)}</tbody></table></>}</div>
    </div>
  </div>
}
